repo:  https://github.com/openwrt/openwrt.git
branch: openwrt-22.03
revision: 977f6f36a0121b213f9eee4a7deb7fdf073320e4
output_dir: ./output

patch_folders:
  - patches_new/base/
  - patches_new/ath79/
  - patches_new/ipq40xx/
  - patches_new/ipq806x/
  - patches_new/ipq807x/
  - patches_new/ramips/
  - patches_new/rest/
  - patches_new/wifi/
  - patches_new/x86/
